'use strict';
const DebtsPage=(()=>{
  let overdue=false;
  function render(){return `<div class="page active"><div class="pg-header"><div class="pg-title-group"><h1 class="pg-title"><div class="pg-title-icon"><i class="fas fa-hand-holding-dollar"></i></div>ديون العملاء</h1><p class="pg-subtitle">متابعة البيع الآجل وتسجيل الدفعات</p></div><div class="pg-actions"><button class="btn btn-ghost" id="debtOverdue"><i class="fas fa-clock"></i> المتأخرة فقط</button></div></div><div class="card"><div class="card-body p0"><div class="tbl-wrap"><table class="dtable"><thead><tr><th>العميل</th><th>الهاتف</th><th>إجمالي الدين</th><th>المدفوع</th><th>المتبقي</th><th>الاستحقاق</th><th>الحالة</th><th></th></tr></thead><tbody id="debtsBody"><tr><td colspan="8">جارٍ التحميل...</td></tr></tbody></table></div></div></div></div>`}
  async function load(){try{const rows=await DB.getDebts(overdue),body=document.getElementById('debtsBody');body.innerHTML=rows.length?rows.map(d=>`<tr><td><strong>${_esc(d.customer_name||'—')}</strong></td><td>${_esc(d.phone||'—')}</td><td>${Fmt.money(d.amount)}</td><td>${Fmt.money(d.paid_amount)}</td><td><strong>${Fmt.money(d.amount-d.paid_amount)}</strong></td><td>${Fmt.dateShort(d.due_date)}</td><td><span class="badge ${d.due_date<new Date().toISOString().slice(0,10)?'bdg-err':'bdg-warn'}">${d.status}</span></td><td><button class="btn btn-primary btn-sm" data-pay="${d.id}" data-max="${d.amount-d.paid_amount}">تسجيل دفعة</button></td></tr>`).join(''):'<tr><td colspan="8"><div class="empty-state"><h3>لا توجد ديون مستحقة</h3></div></td></tr>';body.querySelectorAll('[data-pay]').forEach(b=>b.onclick=()=>pay(b.dataset.pay,+b.dataset.max));}catch(e){Toast.err('خطأ',e.message)}}
  function pay(id,max){Modal.open({title:'تسجيل دفعة',size:'sm',body:`<div class="form-group"><label>قيمة الدفعة (المتبقي ${Fmt.money(max)})</label><input class="form-control" id="debtAmount" type="number" min="0.01" max="${max}" step="0.01"></div>`,foot:'<button class="btn btn-ghost" onclick="Modal.close()">إلغاء</button><button class="btn btn-primary" id="debtSave">حفظ الدفعة</button>'});document.getElementById('debtSave').onclick=async()=>{try{await DB.payDebt(id,+document.getElementById('debtAmount').value);Modal.close();Toast.ok('تم تسجيل الدفعة');load()}catch(e){Toast.err('خطأ',e.message)}}}
  async function afterRender(){document.getElementById('debtOverdue').onclick=()=>{overdue=!overdue;load()};await load()}
  return{render,afterRender};
})();
